version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
