version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8082:8080"
    volumes:
      - ~/.gradle:/home/gradle/.gradle
    depends_on:
      db:
        condition: service_healthy
    networks:
      - project-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - project-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql
    networks:
      project-network:
        aliases:
          - database

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot_certs:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - project-network

  certbot:
    image: certbot/certbot
    entrypoint: >
      /bin/sh -c "trap exit TERM;
      while :; do certbot renew
      --webroot
      --webroot-path=/var/www/certbot &&
      sleep 12h; done;"
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_webroot:/var/www/certbot

networks:
  project-network:
    driver: bridge

volumes:
  db_data:
  jenkins_home:
  certbot_certs:
  certbot_webroot:
