spring:
  application:
    name: respring

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      # authentication-database: admin
      database: ${MONGODB_DATABASE}
      uri: ${MONGODB_URI}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect




logging:
  level:
    org:
      hibernate:
        orm:
          connections:
            pooling: ERROR

file:
  upload-dir: ${FILE_UPLOAD_DIR:${user.home}/uploads}
  # upload-dir: C:/uploads