spring:
  application:
    name: respring

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    activate:
      on-profile: default

  datasource:
    url: jdbc:mysql://i12a307.p.ssafy.io:3306/respring
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      database: respring
      uri: mongodb://ssafy:ssafy@i12a307.p.ssafy.io:27017/respring?authSource=admin

    redis:
      host: i12a307.p.ssafy.io
      port: 6379
      password: ssafy


  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini # gpt-4o-mini
          temperature: 0.7

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  elasticsearch:
    uris: http://i12a307.p.ssafy.io:9200
    username: elastic
    password: changeme

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - profile
              - email

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}

            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id



logging:
  level:
    org:
      hibernate:
        orm:
          connections:
            pooling: ERROR

file:
  upload-dir: ${FILE_UPLOAD_DIR:${user.home}/uploads}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always


cloud:
  aws:
    s3:
      bucket: respring-s3-bucket
    stack.auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA4HWJUICFT7DL6HLO
      secret-key: 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

---
# 🔹 로컬 환경에서 `.env` 파일을 읽도록 설정 (필요한 경우만)
spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local
